// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/calculator": {
    params: {};
  };
  "/faq": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/calculator" | "/faq";
  };
  "routes/calculator.tsx": {
    id: "routes/calculator";
    page: "/calculator";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/faq.tsx": {
    id: "routes/faq";
    page: "/faq";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/calculator": typeof import("./app/routes/calculator.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/faq": typeof import("./app/routes/faq.tsx");
};